 
#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: OpenWrt-LEDE5.4Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
  # release:
    # types: [published]

env:
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai


    - name: ç”µæŠ¥æœºå™¨äººä¿¡æ¯é€šçŸ¥
      run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=ğŸ‰ ä¸»äººï¼š
          æ‚¨æ­£åœ¨ä½¿ç”¨ã€${{github.repository}}ã€‘ä»“åº“çš„ã€${{matrix.target}}ã€‘æ–‡ä»¶å¤¹ç¼–è¯‘å›ºä»¶ä¸­,è¯·è€å¿ƒç­‰å¾…...... ğŸ˜‹" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi
        
   
    - name: ç”µæŠ¥æœºå™¨äººä¿¡æ¯é€šçŸ¥
      run: |
        curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼š
            æ‚¨ä½¿ç”¨ã€${{github.repository}}ã€‘ä»“åº“çš„ã€${{matrix.target}}ã€‘æ–‡ä»¶å¤¹ç¼–è¯‘çš„[${{ env.NAME2 }}-${{ env.NAME1 }}]å›ºä»¶é¡ºåˆ©ç¼–è¯‘å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
          fi
        fi
